spring:
  mail:
    host: 'smtp.office365.com'
    port: 587
    username: ${EMAIL_SENDER_ADDRESS}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        generate_statistics: 'false'
        search:
          default:
            directory_provider: filesystem
            indexBase: ./data/index/default
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    username: admin
    url: jdbc:h2:./data/secureit;DB_CLOSE_ON_EXIT=TRUE
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/database?authSource=admin
  h2:
    # Enabling H2 Console
    console:
      path: /h2-console
      enabled: 'true'
  sql:
    init:
      mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  mvc:
    pathmatch:
      # https://stackoverflow.com/questions/70043841/swagger-2-issue-spring-boot
      matching-strategy: ant-path-matcher
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationSeconds: 864000
    loginAttemptLimit: 5
    # Durations are in expressed of minutes
    loginAttemptTimeWindow: 2
    lockoutDuration: 20
  cors:
    allowedOrigins: http://localhost:4200, http://127.0.0.1:4200
  mailing:
    templatesLocation: 'templates'
    senderAddress: ${EMAIL_SENDER_ADDRESS}
server:
  port: '8001'
